version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis
    container_name: activemq
    ports:
      - "61616:61616"  # JMS port
      - "8161:8161"    # Web console port
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - activemq-data:/var/activemq/data

volumes:
  activemq-data:
